---
# Project Information
site_name: Progression
site_author: AskArthur ArtData LLC.
site_description: Create a progression of recommendations from a user-supplied recommender

# Repository information
repo_name: askarthur/progression
repo_url: https://github.com/askarthur/progression
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 AskArthur ArtData LLC.

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/askarthur
      name: askarthur on GitHub

# Page tree
nav:
  - Home: index.md
